<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateClientesTable2 extends Migration {

    public function up() {
        Schema::create('clientes', function (Blueprint $table) {
            $table->id();
            $table->integer('IdCliente')->nullable();
            $table->string('Tipo', 1)->nullable();
            $table->string('Nome', 100)->nullable();
            $table->string('EnderecoRes', 50)->nullable();
            $table->string('NumeroRes', 10)->nullable();
            $table->string('BairroRes', 20)->nullable();
            $table->string('CepRes', 8)->nullable();
            $table->string('TelefoneRes', 11)->nullable();
            $table->string('EnderecoCom', 50)->nullable();
            $table->string('NumeroCom', 10)->nullable();
            $table->string('BairroCom', 20)->nullable();
            $table->string('CepCom', 8)->nullable();
            $table->string('TelefoneCom', 11)->nullable();
            $table->string('CpfCnpj', 14)->nullable();
            $table->string('RgInscricao', 20)->nullable();
            $table->string('Email', 255)->nullable();
            $table->string('HomePage', 40)->nullable();
            $table->boolean('Bloqueado')->nullable();
            $table->dateTime('UltCompra')->nullable();
            $table->text('Observacoes')->nullable();
            $table->dateTime('Nascimento')->nullable();
            $table->string('Tratamento', 100)->nullable();
            $table->string('Celular', 12)->nullable();
            $table->string('Contato', 60)->nullable();
            $table->dateTime('Cadastro')->nullable();
            $table->string('Identidade', 20)->nullable();
            $table->string('MotivoBloqueio', 255)->nullable();
            $table->decimal('Limite', 19, 4)->nullable();
            $table->boolean('LiberadoGerente')->nullable();
            $table->boolean('ExcessaoBloqueio')->nullable();
            $table->dateTime('NegativadoEm')->nullable();
            $table->integer('VinculoExterno')->nullable();
            $table->integer('IdCidadeRes')->nullable();
            $table->integer('IdCidadeCom')->nullable();
            $table->integer('IdRota')->nullable();
            $table->string('Banco', 30)->nullable();
            $table->string('Agencia', 10)->nullable();
            $table->string('Conta', 20)->nullable();
            $table->integer('ImprimirCheque')->nullable();
            $table->string('NivelPreco', 20)->nullable();
            $table->decimal('LimiteVale', 19, 4)->nullable();
            $table->boolean('Inativo')->nullable();
            $table->string('Proprietario', 16)->nullable();
            $table->string('DataCriacao', 10)->nullable();
            $table->string('HoraCriacao', 10)->nullable();
            $table->string('UsuarioModificacao', 16)->nullable();
            $table->string('DataModificacao', 10)->nullable();
            $table->string('HoraModificacao', 10)->nullable();
            $table->integer('Prazo')->nullable();
            $table->boolean('Bonificacao')->nullable();
            $table->integer('AnpInstalacao')->nullable();
            $table->integer('AnpAtividade')->nullable();
            $table->string('TelefoneResDdd', 3)->nullable();
            $table->string('TelefoneComDdd', 3)->nullable();
            $table->string('celularDdd', 3)->nullable();
            $table->integer('IdTipoBairroRes')->nullable();
            $table->integer('IdTipoBairroCom')->nullable();
            $table->integer('IdTipoLogradouroRes')->nullable();
            $table->integer('IdTipoLogradouroCom')->nullable();
            $table->string('cnae', 7)->nullable();
            $table->string('inscricaoMunicipal', 20)->nullable();
            $table->string('complementoRes', 20)->nullable();
            $table->string('complementoCom', 20)->nullable();
            $table->string('sexo', 1)->nullable();
            $table->string('identidadeOrgao', 10)->nullable();
            $table->string('identidadeEstado', 2)->nullable();
            $table->dateTime('identidadeData')->nullable();
            $table->decimal('ValorBonificacao', 19, 4)->nullable();
            $table->integer('CarenciaBloqueio')->nullable();
            $table->integer('empresaId')->nullable();
            $table->boolean('ImprimirDemonstrativo')->nullable();
            $table->smallInteger('limiteTipo')->nullable();
            $table->smallInteger('contribuinteTipo')->nullable();
            $table->integer('cartaoNumero')->nullable();
            $table->string('cartaoVencimento', 6)->nullable();
            $table->integer('cartaoFaturaPrazo')->nullable();
            $table->integer('cartaoFaturaVencimento')->nullable();
            $table->integer('clienteTipo')->nullable();
            $table->integer('meioPagamentoNumero')->nullable();
            $table->smallInteger('MeioPagamentoForcar')->nullable();
            $table->string('Favorecido', 50)->nullable();
            $table->dateTime('serasaEm')->nullable();
            $table->boolean('importaNovo')->nullable();
            $table->boolean('importaAlterado')->nullable();
            $table->smallInteger('diaBase')->nullable();
            $table->dateTime('dataEvento')->nullable();
            $table->smallInteger('lembreteVencimentos')->nullable();
            $table->smallInteger('requerVeiculoCupom')->nullable();
            $table->decimal('percentualSalario', 19, 4)->nullable();
            $table->dateTime('inativadoEm')->nullable();
            $table->decimal('limiteParcelado', 19, 4)->nullable();
            $table->boolean('clienteCooperado')->nullable();
            $table->integer('clienteCodigoContabil')->nullable();
            $table->string('clienteContador', 50)->nullable();
            $table->boolean('clienteTributacaoUsar')->nullable();
            $table->integer('clienteTributacaoCst')->nullable();
            $table->decimal('clienteTributacaoAliquota', 19, 4)->nullable();
            $table->smallInteger('clienteContribuinteIcms')->nullable();
            $table->string('UsuarioModificacaoTelefone', 16)->nullable();
            $table->string('DataModificacaoTelefone', 10)->nullable();
            $table->string('HoraModificacaoTelefone', 10)->nullable();
            $table->string('UsuarioModificacaoEndereco', 16)->nullable();
            $table->string('DataModificacaoEndereco', 10)->nullable();
            $table->string('HoraModificacaoEndereco', 10)->nullable();
            $table->string('NivelPrecoEx', 20)->nullable();
            $table->dateTime('juridicoEm')->nullable();
            $table->string('favorecidoBancoNumero', 5)->nullable();
            $table->string('favorecidoDocumento', 14)->nullable();
            $table->boolean('bancoDebitarTarifa')->nullable();
            $table->string('telefoneContadorDDD', 3)->nullable();
            $table->string('telefoneContador', 11)->nullable();
            $table->boolean('solicitarAutorizado')->nullable();
            $table->integer('clienteConvenio')->nullable();
            $table->string('favorecidoTipoPessoa', 1)->nullable();
            $table->integer('clienteMaximoParcelasParcelado')->nullable();
            $table->integer('tipoContaBancaria')->nullable();
            $table->boolean('clienteBloqueioDefinitivo')->nullable();
            $table->integer('clienteRotaEntrega')->nullable();
            $table->integer('assembleiaId')->nullable();
            $table->dateTime('assembleiaDtBat')->nullable();
            $table->dateTime('assembleiaDtConv')->nullable();
            $table->dateTime('assembleiaDtBatEs')->nullable();
            $table->integer('assembleiaFuncao')->nullable();
            $table->decimal('DescontoPersonalizado', 19, 4)->nullable();
            $table->string('Hash', 255)->nullable();
            $table->string('NivelPrecoWS', 20)->nullable();
            $table->boolean('ClienteDesconsideraJuros')->nullable();
            $table->integer('Import001')->nullable();
            $table->string('Cor', 10)->nullable();
            $table->boolean('ClienteForcaVenda')->nullable();
            $table->text('InformacoesFinanceiras')->nullable();
            $table->integer('VendedorOrigem')->nullable();
            $table->integer('TipoOrigem')->nullable();
            $table->dateTime('DataOrigem')->nullable();
            $table->dateTime('CriadoEm')->nullable();
            $table->string('CriadoPor', 20)->nullable();
            $table->dateTime('ModificadoEm')->nullable();
            $table->string('ModificadoPor', 20)->nullable();
            $table->string('WhatsApp', 12)->nullable();
            $table->timestamps();
        });
    }

    public function down() {
        Schema::dropIfExists('clientes');
    }
}
